
package mws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DevuelveDNI", targetNamespace = "http://ws.app.com/", wsdlLocation = "http://localhost:8084/DevuelveDNI/DevuelveDNI?wsdl")
public class DevuelveDNI_Service
    extends Service
{

    private final static URL DEVUELVEDNI_WSDL_LOCATION;
    private final static WebServiceException DEVUELVEDNI_EXCEPTION;
    private final static QName DEVUELVEDNI_QNAME = new QName("http://ws.app.com/", "DevuelveDNI");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8084/DevuelveDNI/DevuelveDNI?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEVUELVEDNI_WSDL_LOCATION = url;
        DEVUELVEDNI_EXCEPTION = e;
    }

    public DevuelveDNI_Service() {
        super(__getWsdlLocation(), DEVUELVEDNI_QNAME);
    }

    public DevuelveDNI_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEVUELVEDNI_QNAME, features);
    }

    public DevuelveDNI_Service(URL wsdlLocation) {
        super(wsdlLocation, DEVUELVEDNI_QNAME);
    }

    public DevuelveDNI_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEVUELVEDNI_QNAME, features);
    }

    public DevuelveDNI_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DevuelveDNI_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DevuelveDNI
     */
    @WebEndpoint(name = "DevuelveDNIPort")
    public DevuelveDNI getDevuelveDNIPort() {
        return super.getPort(new QName("http://ws.app.com/", "DevuelveDNIPort"), DevuelveDNI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DevuelveDNI
     */
    @WebEndpoint(name = "DevuelveDNIPort")
    public DevuelveDNI getDevuelveDNIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.app.com/", "DevuelveDNIPort"), DevuelveDNI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEVUELVEDNI_EXCEPTION!= null) {
            throw DEVUELVEDNI_EXCEPTION;
        }
        return DEVUELVEDNI_WSDL_LOCATION;
    }

}
