
package ws.meteor;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSMeteorologico", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://www.imn.ac.cr/MeteorologicoWS/MeteorologicoWS.asmx?WSDL")
public class WSMeteorologico
    extends Service
{

    private final static URL WSMETEOROLOGICO_WSDL_LOCATION;
    private final static WebServiceException WSMETEOROLOGICO_EXCEPTION;
    private final static QName WSMETEOROLOGICO_QNAME = new QName("http://tempuri.org/", "WSMeteorologico");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.imn.ac.cr/MeteorologicoWS/MeteorologicoWS.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSMETEOROLOGICO_WSDL_LOCATION = url;
        WSMETEOROLOGICO_EXCEPTION = e;
    }

    public WSMeteorologico() {
        super(__getWsdlLocation(), WSMETEOROLOGICO_QNAME);
    }

    public WSMeteorologico(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSMETEOROLOGICO_QNAME, features);
    }

    public WSMeteorologico(URL wsdlLocation) {
        super(wsdlLocation, WSMETEOROLOGICO_QNAME);
    }

    public WSMeteorologico(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSMETEOROLOGICO_QNAME, features);
    }

    public WSMeteorologico(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSMeteorologico(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSMeteorologicoSoap
     */
    @WebEndpoint(name = "WSMeteorologicoSoap")
    public WSMeteorologicoSoap getWSMeteorologicoSoap() {
        return super.getPort(new QName("http://tempuri.org/", "WSMeteorologicoSoap"), WSMeteorologicoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSMeteorologicoSoap
     */
    @WebEndpoint(name = "WSMeteorologicoSoap")
    public WSMeteorologicoSoap getWSMeteorologicoSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WSMeteorologicoSoap"), WSMeteorologicoSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns WSMeteorologicoSoap
     */
    @WebEndpoint(name = "WSMeteorologicoSoap12")
    public WSMeteorologicoSoap getWSMeteorologicoSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "WSMeteorologicoSoap12"), WSMeteorologicoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSMeteorologicoSoap
     */
    @WebEndpoint(name = "WSMeteorologicoSoap12")
    public WSMeteorologicoSoap getWSMeteorologicoSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WSMeteorologicoSoap12"), WSMeteorologicoSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns WSMeteorologicoHttpGet
     */
    @WebEndpoint(name = "WSMeteorologicoHttpGet")
    public WSMeteorologicoHttpGet getWSMeteorologicoHttpGet() {
        return super.getPort(new QName("http://tempuri.org/", "WSMeteorologicoHttpGet"), WSMeteorologicoHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSMeteorologicoHttpGet
     */
    @WebEndpoint(name = "WSMeteorologicoHttpGet")
    public WSMeteorologicoHttpGet getWSMeteorologicoHttpGet(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WSMeteorologicoHttpGet"), WSMeteorologicoHttpGet.class, features);
    }

    /**
     * 
     * @return
     *     returns WSMeteorologicoHttpPost
     */
    @WebEndpoint(name = "WSMeteorologicoHttpPost")
    public WSMeteorologicoHttpPost getWSMeteorologicoHttpPost() {
        return super.getPort(new QName("http://tempuri.org/", "WSMeteorologicoHttpPost"), WSMeteorologicoHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSMeteorologicoHttpPost
     */
    @WebEndpoint(name = "WSMeteorologicoHttpPost")
    public WSMeteorologicoHttpPost getWSMeteorologicoHttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WSMeteorologicoHttpPost"), WSMeteorologicoHttpPost.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSMETEOROLOGICO_EXCEPTION!= null) {
            throw WSMETEOROLOGICO_EXCEPTION;
        }
        return WSMETEOROLOGICO_WSDL_LOCATION;
    }

}
